tap "homebrew/bundle"
tap "homebrew/services"
tap "tbckr/tap"
brew "zstd"
brew "openssl@3"
brew "mise"
brew "aspell"
brew "colima"
brew "direnv"
brew "docker"
brew "docker-compose"
brew "duti"
brew "fish"
brew "fisher"
brew "flyctl"
brew "geckodriver"
brew "gh"
brew "gnu-sed"
brew "gnupg"
brew "httpie"
brew "iperf3"
brew "jq"
brew "libpq"
brew "mas"
brew "openssl@1.1"
brew "pinentry-mac"
brew "postgresql@14", restart_service: true
brew "pv"
brew "pwgen"
brew "rcm"
brew "speedtest-cli"
brew "squashfs"
brew "tailwindcss"
brew "tree"
brew "vips"
brew "watch"
brew "wifi-password"
brew "tbckr/tap/sgpt"
cask "betterzip"
cask "calibre"
cask "chromedriver"
cask "copyclip"
cask "crossover"
cask "discord"
cask "dolphin"
cask "finicky"
cask "firefox"
cask "google-chrome"
cask "heroic"
cask "iterm2"
cask "karabiner-elements"
cask "krisp"
cask "livebook"
cask "lunar"
cask "netnewswire"
cask "notion"
cask "qflipper"
cask "qlmarkdown"
cask "qlstephen"
cask "rectangle"
cask "secretive"
cask "semulov"
cask "slack"
cask "spotify"
cask "syntax-highlight"
cask "typora"
cask "uhk-agent"
cask "ukelele"
cask "visual-studio-code"
cask "vlc"
cask "whatsapp"
mas "1Blocker", id: 1365531024
mas "Amphetamine", id: 937984704
mas "Baking Soda", id: 1601151613
mas "DigiDoc4 Client", id: 1370791134
mas "Gifski", id: 1351639930
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Surfshark", id: 1437809329
mas "Telegram", id: 747648890
mas "VictronConnect", id: 1084677271
mas "Vinegar", id: 1591303229
mas "Web eID", id: 1576665083
vscode "adpyke.vscode-sql-formatter"
vscode "bmalehorn.vscode-fish"
vscode "bradlc.vscode-tailwindcss"
vscode "dotjoshjohnson.xml"
vscode "eamodio.gitlens"
vscode "editorconfig.editorconfig"
vscode "esbenp.prettier-vscode"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "github.vscode-github-actions"
vscode "hashicorp.terraform"
vscode "lexical-lsp.lexical"
vscode "marp-team.marp-vscode"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.debugpy"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vsliveshare.vsliveshare"
vscode "orta.vscode-jest"
vscode "phoenixframework.phoenix"
vscode "pucelle.vscode-css-navigation"
vscode "shopify.ruby-lsp"
vscode "tamasfe.even-better-toml"
vscode "waderyan.gitblame"
