{
  inputs,
  lib,
  pkgs,
  username,
  ...
}:
let
  hm = inputs.home-manager.lib.hm;
  hasSopsKey = builtins.pathExists "/Users/${username}/.config/sops/age/keys.txt";
in
{
  # Home-manager configuration to generate MCP env vars for shell tools
  # Only enabled when sops age key exists on this machine
  home-manager.users.${username} =
    { osConfig, ... }:
    {
      home.activation = lib.mkIf hasSopsKey {
        writeMcpSecrets = hm.dag.entryAfter [ "writeBoundary" ] ''
          echo "Writing MCP secrets..."

          mkdir -p /Users/${username}/.config/fish/conf.d
          mkdir -p /Users/${username}/.config/zsh

          # Only proceed if secrets exist to avoid errors
          if [ -f "${osConfig.sops.secrets.githits_api_key.path}" ] && [ -f "${osConfig.sops.secrets.context7_api_key.path}" ]; then
            GITHITS_KEY=$(cat ${osConfig.sops.secrets.githits_api_key.path})
            CONTEXT7_KEY=$(cat ${osConfig.sops.secrets.context7_api_key.path})

            # Use printf to avoid heredoc issues
            printf "# This file is generated by nix-darwin\\n# Do not edit manually\\n\\nset -gx GITHITS_API_TOKEN \\"%s\\"\\nset -gx CONTEXT7_API_KEY \\"%s\\"\\n" "$GITHITS_KEY" "$CONTEXT7_KEY" > /Users/${username}/.config/fish/conf.d/mcp_secrets.fish
            printf "# This file is generated by nix-darwin\n# Do not edit manually\n\nexport GITHITS_API_TOKEN=\"%s\"\nexport CONTEXT7_API_KEY=\"%s\"\n" "$GITHITS_KEY" "$CONTEXT7_KEY" > /Users/${username}/.config/zsh/mcp_secrets.zsh

            if [ -f /Users/${username}/.zshenv ]; then
              if ! ${lib.getExe pkgs.gnugrep} -Fq '. "$HOME/.config/zsh/mcp_secrets.zsh"' /Users/${username}/.zshenv; then
                printf '\n. "$HOME/.config/zsh/mcp_secrets.zsh"\n' >> /Users/${username}/.zshenv
              fi
            else
              printf '. "$HOME/.cargo/env"\n. "$HOME/.config/zsh/mcp_secrets.zsh"\n' > /Users/${username}/.zshenv
            fi

            launchctl setenv GITHITS_API_TOKEN "$GITHITS_KEY"
            launchctl setenv CONTEXT7_API_KEY "$CONTEXT7_KEY"

            # Secure the file (only readable by user)
            chmod 600 /Users/${username}/.config/fish/conf.d/mcp_secrets.fish
            chmod 600 /Users/${username}/.config/zsh/mcp_secrets.zsh
            chmod 600 /Users/${username}/.zshenv
          else
            echo "Warning: MCP secrets not found, skipping MCP env generation"
          fi
        '';
      };
    };
}
