{
  inputs,
  lib,
  pkgs,
  username,
  ...
}:
let
  hm = inputs.home-manager.lib.hm;
  envVars = {
    GITHITS_API_TOKEN = "githits_api_key";
    CONTEXT7_API_KEY = "context7_api_key";
    STITCH_API_KEY = "stitch_api_key";
  };
in
{
  # Home-manager configuration to expose MCP env vars to shell tools (e.g. Codex)
  home-manager.users.${username} =
    { osConfig, ... }:
    let
      secretPath = secret: osConfig.sops.secrets.${secret}.path;
      # Keys are read from /run/secrets when the shell starts, so these files hold no secrets
      fishLines = lib.mapAttrsToList (
        var: secret: "test -r ${secretPath secret}; and set -gx ${var} (cat ${secretPath secret})"
      ) envVars;
      zshLines = lib.mapAttrsToList (
        var: secret: "[ -r ${secretPath secret} ] && export ${var}=\"$(< ${secretPath secret})\""
      ) envVars;
    in
    {
      home.activation = {
        writeMcpSecrets = hm.dag.entryAfter [ "writeBoundary" ] ''
          echo "Writing MCP secret loaders..."

          mkdir -p /Users/${username}/.config/fish/conf.d
          mkdir -p /Users/${username}/.config/zsh

          printf '%s\n' "# This file is generated by nix-darwin" "# Do not edit manually" ${lib.escapeShellArgs fishLines} > /Users/${username}/.config/fish/conf.d/mcp_secrets.fish
          printf '%s\n' "# This file is generated by nix-darwin" "# Do not edit manually" ${lib.escapeShellArgs zshLines} > /Users/${username}/.config/zsh/mcp_secrets.zsh

          if [ -f /Users/${username}/.zshenv ]; then
            if ! ${lib.getExe pkgs.gnugrep} -Fq '. "$HOME/.config/zsh/mcp_secrets.zsh"' /Users/${username}/.zshenv; then
              printf '\n. "$HOME/.config/zsh/mcp_secrets.zsh"\n' >> /Users/${username}/.zshenv
            fi
          else
            printf '. "$HOME/.cargo/env"\n. "$HOME/.config/zsh/mcp_secrets.zsh"\n' > /Users/${username}/.zshenv
          fi
        '';
      };
    };
}
